#!/bin/bash

# Gyakorlattár szűrők tesztelése

echo "🧪 Gyakorlattár szűrők tesztelése"
echo ""

# Check if the app is running
if ! curl -s http://localhost:5173 > /dev/null 2>&1; then
    echo "⚠️  Az alkalmazás nem fut a http://localhost:5173 címen"
    echo "Először indítsd el: npm run dev"
    exit 1
fi

echo "✅ Az alkalmazás fut"
echo ""
echo "📋 Teszt lépések:"
echo ""
echo "1. Nyisd meg a böngészőben: http://localhost:5173/exercises"
echo ""
echo "2. Ellenőrizd a kategória szűrőket:"
echo "   ✅ Erősítő edzés"
echo "   ✅ Cardio"
echo "   ✅ Kettlebell"
echo "   ✅ Mobilitás és nyújtás"
echo "   ✅ HIIT"
echo "   ✅ Regeneráció"
echo "   ✅ FMS korrekció ⭐ ÚJ"
echo "   ✅ SMR (Henger) ⭐ ÚJ"
echo ""
echo "3. Tesztek:"
echo ""
echo "   A) FMS szűrő teszt:"
echo "      - Válaszd ki: 'FMS korrekció'"
echo "      - Várt eredmény: FMS korrekciós gyakorlatok (pl. 'Bird dog', 'Plank hold', stb.)"
echo ""
echo "   B) SMR szűrő teszt:"
echo "      - Válaszd ki: 'SMR (Henger)'"
echo "      - Várt eredmény: SMR gyakorlatok (pl. 'SMR - Vádli', 'SMR - Comb hátsó', stb.)"
echo ""
echo "   C) Kettlebell szűrő teszt:"
echo "      - Válaszd ki: 'Kettlebell'"
echo "      - Várt eredmény: Kettlebell gyakorlatok (nem FMS, nem SMR)"
echo ""
echo "4. Mozgásminta szűrők tesztelése:"
echo ""
echo "   A) FMS kategóriában:"
echo "      - Várt mozgásminták: ASLR korrekció, SM korrekció, Stabilitás korrekció, stb."
echo ""
echo "   B) SMR kategóriában:"
echo "      - Várt mozgásminta: Mobilizálás"
echo ""
echo "   C) Kettlebell kategóriában:"
echo "      - Várt mozgásminták: Csípő/Térd domináns, Nyomó/Húzó mozgások, stb."
echo ""
echo "5. Keresés teszt:"
echo "   - Írj be: 'SMR'"
echo "   - Várt eredmény: Összes SMR gyakorlat"
echo "   - Írj be: 'FMS'"
echo "   - Várt eredmény: FMS gyakorlatok"
echo "   - Írj be: 'kettlebell'"
echo "   - Várt eredmény: Kettlebell gyakorlatok"
echo ""
echo "✨ Ha minden működik, a szűrők sikeresen javítva lettek!"
