#!/bin/bash

# Gyakorlatok kategóriáinak teljes ellenőrzése és javítása

echo "🔍 Gyakorlatok adatbázis ellenőrzése és javítása"
echo ""
echo "Ez a folyamat 3 lépésből áll:"
echo ""
echo "📋 LÉPÉS 1: Jelenlegi állapot ellenőrzése"
echo "📋 LÉPÉS 2: Enum értékek hozzáadása (ha még nem történt meg)"
echo "📋 LÉPÉS 3: Összes gyakorlat kategóriájának pontos beállítása"
echo ""
echo "⚠️  Nyisd meg a Supabase SQL Editor-t:"
echo "   https://supabase.com/dashboard/project/YOUR_PROJECT/sql"
echo ""
read -p "Folytatod? (i/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Ii]$ ]]
then
    echo "❌ Megszakítva."
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 LÉPÉS 1: Jelenlegi állapot ellenőrzése"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Másold be és futtasd le ezt a scriptet:"
echo "📄 Fájl: check_current_exercises.sql"
echo ""
echo "Ez megmutatja:"
echo "  • Milyen kategóriák vannak használatban"
echo "  • Hány gyakorlat van minden kategóriában"
echo "  • Milyen mozgásminták vannak"
echo "  • Mely gyakorlatok vannak rossz kategóriában"
echo ""
echo "A fájl teljes elérési útja:"
echo "  $(pwd)/check_current_exercises.sql"
echo ""
read -p "Nyomd meg az Enter-t ha lefuttattad és megnézted az eredményeket..."
read

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 LÉPÉS 2: Enum értékek hozzáadása (ha szükséges)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ha az előző lépés során láttad hogy NEM létezik 'fms' és 'smr' kategória,"
echo "akkor futtasd le ezt a scriptet:"
echo "📄 Fájl: add_fms_smr_categories.sql"
echo ""
echo "Ha már léteznek ezek a kategóriák, ugorj a következő lépésre."
echo ""
echo "A fájl teljes elérési útja:"
echo "  $(pwd)/add_fms_smr_categories.sql"
echo ""
read -p "Nyomd meg az Enter-t a folytatáshoz..."
read

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 LÉPÉS 3: Összes gyakorlat kategóriájának javítása"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Most futtasd le a kategóriák javító scriptet:"
echo "📄 Fájl: fix_all_exercise_categories.sql"
echo ""
echo "Ez automatikusan:"
echo "  ✅ Áthelyezi az FMS gyakorlatokat az 'fms' kategóriába"
echo "  ✅ Áthelyezi az SMR gyakorlatokat az 'smr' kategóriába"
echo "  ✅ Beállítja a kettlebell gyakorlatokat"
echo "  ✅ Ellenőrzi az eredményeket"
echo ""
echo "A fájl teljes elérési útja:"
echo "  $(pwd)/fix_all_exercise_categories.sql"
echo ""
read -p "Nyomd meg az Enter-t ha lefuttattad..."
read

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ KATEGÓRIÁK FRISSÍTVE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "A script lefuttatása után az alábbi kategóriák működnek:"
echo ""
echo "  ✅ FMS korrekció     - FMS korrekciós gyakorlatok"
echo "  ✅ SMR (Henger)      - Hengeres mobilizáló gyakorlatok"
echo "  ✅ Kettlebell        - Kettlebell specifikus gyakorlatok"
echo "  ✅ Erősítő edzés     - Általános erősítő gyakorlatok"
echo "  ✅ Cardio            - Kardió gyakorlatok"
echo "  ✅ Mobilitás         - Mobilitás és nyújtás"
echo "  ✅ HIIT              - Magas intenzitású gyakorlatok"
echo "  ✅ Regeneráció       - Regenerációs gyakorlatok"
echo ""
echo "🎯 Következő lépések:"
echo ""
echo "1. Frissítsd az alkalmazást a böngészőben (F5)"
echo "2. Menj a Gyakorlattárba"
echo "3. Próbáld ki az új szűrőket:"
echo "   • FMS korrekció - csak FMS gyakorlatok"
echo "   • SMR (Henger) - csak SMR gyakorlatok"
echo "   • Kettlebell - csak Kettlebell gyakorlatok"
echo ""
echo "✨ Kész! A szűrők most már pontosan működnek!"
