import type { ExerciseCategory, MovementPattern, FMSFocusId } from './types';

export const EXERCISE_CATEGORY_OPTIONS: { id: ExerciseCategory; label: string }[] = [
  { id: 'strength_training', label: 'Erőedzés' },
  { id: 'cardio', label: 'Kardió' },
  { id: 'kettlebell', label: 'Kettlebell' },
  { id: 'mobility_flexibility', label: 'Mobilitás/Nyújtás' },
  { id: 'hiit', label: 'HIIT' },
  { id: 'recovery', label: 'Regeneráció' },
  { id: 'fms', label: 'FMS' },
  { id: 'smr', label: 'SMR' },
];

export const EXERCISE_CATEGORY_MOVEMENT_PATTERNS: Record<ExerciseCategory, MovementPattern[]> = {
  kettlebell: [
    'gait_stability',
    'gait_crawling',
    'hip_dominant_bilateral',
    'hip_dominant_unilateral',
    'knee_dominant_bilateral',
    'knee_dominant_unilateral',
    'horizontal_push_bilateral',
    'horizontal_push_unilateral',
    'horizontal_pull_bilateral',
    'horizontal_pull_unilateral',
    'vertical_push_bilateral',
    'vertical_push_unilateral',
    'vertical_pull_bilateral',
    'stability_anti_extension',
    'stability_anti_rotation',
    'stability_anti_flexion',
    'core_other',
    'local_exercises',
  ],
  fms: [
    'aslr_correction_first',
    'aslr_correction_second',
    'sm_correction_first',
    'sm_correction_second',
    'stability_correction',
    'upper_body_mobility',
    'mobilization',
    'stability_anti_extension',
    'stability_anti_rotation',
    'stability_anti_flexion',
    'knee_dominant_bilateral',
    'knee_dominant_unilateral',
    'hip_dominant_bilateral',
    'hip_dominant_unilateral',
    'horizontal_push_bilateral',
    'core_other',
  ],
  smr: [
    'mobilization',
  ],
  mobility_flexibility: [
    'upper_body_mobility',
    'mobilization',
  ],
  strength_training: [
    'hip_dominant_bilateral',
    'hip_dominant_unilateral',
    'knee_dominant_bilateral',
    'knee_dominant_unilateral',
    'horizontal_push_bilateral',
    'horizontal_push_unilateral',
    'horizontal_pull_bilateral',
    'horizontal_pull_unilateral',
    'vertical_push_bilateral',
    'vertical_push_unilateral',
    'vertical_pull_bilateral',
    'stability_anti_extension',
    'stability_anti_rotation',
    'stability_anti_flexion',
    'core_other',
    'gait_stability',
    'gait_crawling',
  ],
  cardio: [
    'gait_stability',
    'gait_crawling',
  ],
  hiit: [
    'gait_stability',
    'gait_crawling',
    'hip_dominant_bilateral',
    'knee_dominant_bilateral',
    'stability_anti_extension',
    'stability_anti_rotation',
    'stability_anti_flexion',
    'core_other',
  ],
  recovery: [
    'mobilization',
    'upper_body_mobility',
    'stability_anti_extension',
    'stability_anti_rotation',
    'stability_anti_flexion',
    'core_other',
    'gait_stability',
  ],
};

export const MOVEMENT_PATTERN_OPTIONS: { id: MovementPattern; label: string; category?: string }[] = [
  { id: 'gait_stability', label: 'Gait – törzs stabilitás', category: 'Gait' },
  { id: 'gait_crawling', label: 'Gait mászásban – törzs stabilitás', category: 'Gait' },
  { id: 'hip_dominant_bilateral', label: 'Csípő domináns – bilaterális', category: 'Csípő' },
  { id: 'hip_dominant_unilateral', label: 'Csípő domináns – unilaterális', category: 'Csípő' },
  { id: 'knee_dominant_bilateral', label: 'Térd domináns – bilaterális', category: 'Térd' },
  { id: 'knee_dominant_unilateral', label: 'Térd domináns – unilaterális', category: 'Térd' },
  { id: 'horizontal_push_bilateral', label: 'Horizontális nyomás – bilaterális', category: 'Horizontális' },
  { id: 'horizontal_push_unilateral', label: 'Horizontális nyomás – unilaterális', category: 'Horizontális' },
  { id: 'horizontal_pull_bilateral', label: 'Horizontális húzás – bilaterális', category: 'Horizontális' },
  { id: 'horizontal_pull_unilateral', label: 'Horizontális húzás – unilaterális', category: 'Horizontális' },
  { id: 'vertical_push_bilateral', label: 'Vertikális nyomás – bilaterális', category: 'Vertikális' },
  { id: 'vertical_push_unilateral', label: 'Vertikális nyomás – unilaterális', category: 'Vertikális' },
  { id: 'vertical_pull_bilateral', label: 'Vertikális húzás – bilaterális', category: 'Vertikális' },
  { id: 'stability_anti_extension', label: 'Stabilitás – anti-extenzió', category: 'Stabilitás' },
  { id: 'stability_anti_rotation', label: 'Stabilitás – anti-rotáció', category: 'Stabilitás' },
  { id: 'stability_anti_flexion', label: 'Stabilitás – anti-flexió', category: 'Stabilitás' },
  { id: 'core_other', label: 'Core – egyéb', category: 'Stabilitás' },
  { id: 'local_exercises', label: 'Lokális gyakorlatok', category: 'Korrekció' },
  { id: 'upper_body_mobility', label: 'Felsőtest mobilizálás', category: 'Korrekció' },
  { id: 'aslr_correction_first', label: 'ASLR korrekció – első pár', category: 'Korrekció' },
  { id: 'aslr_correction_second', label: 'ASLR korrekció – második hármas', category: 'Korrekció' },
  { id: 'sm_correction_first', label: 'SM korrekció – első pár', category: 'Korrekció' },
  { id: 'sm_correction_second', label: 'SM korrekció – második hármas', category: 'Korrekció' },
  { id: 'stability_correction', label: 'Stabilitás korrekció', category: 'Korrekció' },
  { id: 'mobilization', label: 'Mobilizálás', category: 'Korrekció' },
];

export const FMS_FOCUS_OPTIONS: { id: FMSFocusId; label: string }[] = [
  { id: 'deep_squat', label: 'Mély guggolás' },
  { id: 'hurdle_step', label: 'Akadálylépés' },
  { id: 'inline_lunge', label: 'Inline kitörés' },
  { id: 'shoulder_mobility', label: 'Vállmobilitás' },
  { id: 'active_straight_leg_raise', label: 'Aktív nyújtott lábemelés' },
  { id: 'trunk_stability_pushup', label: 'Törzsstabil fekvőtámasz' },
  { id: 'rotary_stability', label: 'Rotációs stabilitás' },
];

export const FMS_FOCUS_EXERCISE_NAMES: Record<FMSFocusId, string[]> = {
  deep_squat: [
    'assisted deep squat with band',
    'goblet squat hold',
    'ankle dorsiflexion mobilization',
    'quadruped rocking',
    'overhead squat with dowel',
  ],
  hurdle_step: [
    'mini-band march',
    'single-leg deadlift (unloaded)',
    'heel-to-wall march',
    'assisted step-over',
    'standing hip flexor mobilization',
  ],
  inline_lunge: [
    'split squat hold',
    'assisted in-line lunge with band',
    'half kneeling chop/lift with band',
    'ankle dorsiflexion mobilization (front leg)',
    'hip flexor stretch (rear leg)',
  ],
  shoulder_mobility: [
    'thread the needle',
    'open book stretch',
    'wall slides',
    'banded shoulder dislocates',
    'quadruped thoracic rotation',
    'shoulder clearing - thread the needle',
    'wall slides (clearing)',
    'banded external rotation',
  ],
  active_straight_leg_raise: [
    'single leg lowering with band',
    'assisted straight leg raise',
    'half kneeling hip flexor stretch',
    'toe touch progression',
    'cook hip lift',
  ],
  trunk_stability_pushup: [
    'plank hold',
    'push-up plus',
    'dead bug',
    'tall plank shoulder taps',
    'quadruped hover (bear hold)',
  ],
  rotary_stability: [
    'bird dog',
    'side plank variations',
    'dead bug (rotary)',
    'pallof press with band',
    'quadruped diagonals',
  ],
};

export const LEGACY_CATEGORY_TO_TAXONOMY_SLUG: Record<ExerciseCategory, string> = {
  strength_training: 'strength',
  cardio: 'cardio',
  kettlebell: 'kettlebell',
  mobility_flexibility: 'mobility',
  hiit: 'hiit',
  recovery: 'recovery',
  fms: 'fms',
  smr: 'smr',
};

export const EXACT_PATTERN_TO_TAXONOMY_SLUG: Record<MovementPattern, string> = {
  gait_stability: 'gait_stability',
  gait_crawling: 'gait_crawling',
  hip_dominant_bilateral: 'hip_dominant_bilateral',
  hip_dominant_unilateral: 'hip_dominant_unilateral',
  knee_dominant_bilateral: 'knee_dominant_bilateral',
  knee_dominant_unilateral: 'knee_dominant_unilateral',
  horizontal_push_bilateral: 'horizontal_push_bilateral',
  horizontal_push_unilateral: 'horizontal_push_unilateral',
  horizontal_pull_bilateral: 'horizontal_pull_bilateral',
  horizontal_pull_unilateral: 'horizontal_pull_unilateral',
  vertical_push_bilateral: 'vertical_push_bilateral',
  vertical_push_unilateral: 'vertical_push_unilateral',
  vertical_pull_bilateral: 'vertical_pull_bilateral',
  stability_anti_extension: 'stability_anti_extension',
  stability_anti_rotation: 'stability_anti_rotation',
  stability_anti_flexion: 'stability_anti_flexion',
  core_other: 'core_other',
  local_exercises: 'local_exercises',
  upper_body_mobility: 'upper_body_mobility_pattern',
  aslr_correction_first: 'aslr_correction_first',
  aslr_correction_second: 'aslr_correction_second',
  sm_correction_first: 'sm_correction_first',
  sm_correction_second: 'sm_correction_second',
  stability_correction: 'stability_correction_pattern',
  mobilization: 'mobilization_pattern',
};

export const PATTERN_FAMILY_AND_LATERALITY_TAGS: Record<MovementPattern, string[]> = {
  gait_stability: ['gait', 'locomotion'],
  gait_crawling: ['gait', 'locomotion'],
  hip_dominant_bilateral: ['hip_dominant', 'bilateral'],
  hip_dominant_unilateral: ['hip_dominant', 'unilateral'],
  knee_dominant_bilateral: ['knee_dominant', 'bilateral'],
  knee_dominant_unilateral: ['knee_dominant', 'unilateral'],
  horizontal_push_bilateral: ['horizontal_push', 'bilateral'],
  horizontal_push_unilateral: ['horizontal_push', 'unilateral'],
  horizontal_pull_bilateral: ['horizontal_pull', 'bilateral'],
  horizontal_pull_unilateral: ['horizontal_pull', 'unilateral'],
  vertical_push_bilateral: ['vertical_push', 'bilateral'],
  vertical_push_unilateral: ['vertical_push', 'unilateral'],
  vertical_pull_bilateral: ['vertical_pull', 'bilateral'],
  stability_anti_extension: ['anti_extension', 'core'],
  stability_anti_rotation: ['anti_rotation', 'core'],
  stability_anti_flexion: ['anti_flexion', 'core'],
  core_other: ['core'],
  local_exercises: ['local_exercise'],
  upper_body_mobility: ['upper_body_mobility'],
  aslr_correction_first: ['fms'],
  aslr_correction_second: ['fms'],
  sm_correction_first: ['fms'],
  sm_correction_second: ['fms'],
  stability_correction: ['stability_correction'],
  mobilization: ['mobilization'],
};

export const FILTERABLE_PATTERN_FAMILY_SLUGS = new Set([
  'gait',
  'hip_dominant',
  'knee_dominant',
  'horizontal_push',
  'horizontal_pull',
  'vertical_push',
  'vertical_pull',
  'anti_extension',
  'anti_rotation',
  'anti_flexion',
  'core',
  'local_exercise',
  'upper_body_mobility',
  'mobilization',
  'stability_correction',
]);

export const FILTERABLE_LATERALITY_SLUGS = new Set([
  'bilateral',
  'unilateral',
  'locomotion',
]);
